### ISSUE TITLE
I found a  vulnerability can getshell  in index.php 

### ISSUE THREAD

**Issue by liao10086** [robiso/wondercms#137]
version:2.7.0

![image](https://user-images.githubusercontent.com/37523122/56418873-e49e3480-62ca-11e9-9948-fb8e077315a1.png)

Sep1:
Because the system leaked the password, if admin do not change password you can log in directly.
![image](https://user-images.githubusercontent.com/37523122/56418173-c20b1c00-62c8-11e9-8955-0705e9730baa.png)
Sep2:
settings->themes&plugins
Input hacker zip link  like:http://10.11.33.206:8088/ZIPFromURL.zip
![image](https://user-images.githubusercontent.com/37523122/56418415-7311b680-62c9-11e9-96d1-b6e3a6e04159.png)
Sep3:
After install visit http://10.20.3.130/themes/theme.php hacker php code was executed.
So you can see I write  `<?php phpinfo(); ?>` was executed
![image](https://user-images.githubusercontent.com/37523122/56418563-d13e9980-62c9-11e9-8bb1-10a60caafc5d.png)
POC:
![image](https://user-images.githubusercontent.com/37523122/56418922-18795a00-62cb-11e9-9a07-6f904f6f1ccf.png)

 Suggest：
1. Add .htaccess file disallow access to themes and plugins directories.
2.Check the input link source wheater https://www.wondercms.com/
3.Don't leaked the password

I hope you can fix it.
author by:xijun.liao@dbappsecurity.com.cn

**Comment by robiso** [comment]
@liao10086, thanks for taking the time and looking into WonderCMS.
This is not really a vulnerability, since you're logging in with default generated credentials.

What you've shown in the proof of concept is basically a self attack.
We shouldn't be adding "verifications" for the themes and plugins, as developers can add their own themes/plugins and provide them via a 3rd party service.

We however warn WonderCMS users to install themes/plugins from wondercms.com only, but we don't limit them to this.

Also, the admin is actioned to immediately change the login URL and password after logging in. We cannot solve the problem of admins not changing their credentials and login URL and it's up to the admin to be careful.

I don't really think this requires "fixing".

Closing issue, please feel free to comment or direct others to this topic for further discussion.

**Comment by NicolasCARPi** [comment]
Agreed, if you login as admin you can do what you want, that's the expected behavior...

**Comment by liao10086** [comment]
This is a back-end vulnerability that requires privileges. If the leak of administrator information is a disaster directly, you can add a .htaccess file to prevent attackers from accessing themes and plugins directories directly and reduce the risk.
If attacker getshell it's going to be a devastating blow to websites.

**Comment by robiso** [comment]
@liao10086, if an attacker gains access to the admin, he can practically deface the whole website as it is.

We could white list the themes and plugins URL installer and there would still be numerous ways of an attacker to deface the website if he had the admin password
