### ISSUE TITLE
Cookie consent Plugin is missing

### ISSUE THREAD

**Issue by TechArea** [robiso/wondercms#155]
Hi
I searched few minutes, but could not find a cookie consent plugin or any function in this direction.
I think that this is a necessary feature, no mater if solved with a plugin or build-in solution.

Thanks in advance

Best regards

**Comment by StephanStanisic** [comment]
Hi @TechArea,

I don't really see the need for a cookie consent plugin as WonderCMS doesn't use any cookies for "normal" visits. Only when you, as admin, log in a cookie is created.

But, since I do think this is something that can come in handy if you use cookies, I created a quick plugin for displaying a simple cookie message.

You can find the github repo here: https://github.com/StephanStanisic/addon-cookie-message/
(It is for WonderCMS 3.0.0)

Example can be found here: https://demo1.wonder.stanisic.nl

**Comment by robiso** [comment]
@StephanStanisic, awesome of you for explaining and providing a solution. Much appreciated and welcome! )

Thank you!
