### ISSUE TITLE
Implements editing of subside

### ISSUE THREAD

**Issue by MatthewSaintBull** [robiso/wondercms#160]
Hi, 
I'm using this CMS for a little project and I'm facing in an Issue:
I need to implement a self made plugin which implements the newsletter form inside subside section. 
To do this, I've edited the kernel of the CMS and added the hook for subside section.
The problem is that if an update will come, I'll have some problems for the kernel edits. Isn't possible to add this as hook or make a public method like 'addHook'?
I think that could be awesome for customization of this CMS.

Sorry for my english but I'm doing the best.

Bye,

Matteo

**Comment by StephanStanisic** [comment]
Hi Matteo,

If I understand correctly, you'd like to add a newsletter subscription `form` element (like one from mailchimp) into the subside section without editing `index.php`.

The best way to do this would be to edit the theme you're using, since this doesn't get updated when WonderCMS does.

For example, with the default "mint" theme you could edit [`theme.php` on line 53](https://github.com/robiso/wondercms/blob/master/themes/default/theme.php#L53)  onward, that is where the subside portion is.

If you'd like to do this without editing the `theme.php` file, you could just add it to the block contents of the page. If you disable the summernote editor plugin you can edit the HTML directly, and add your form there.

As for doing this with a plugin, that's really hard since you'd need to use a DOMDocument to interpret the HTML and then add the form afterward. But since this is als theme specific I'd advice just adding the form to the `theme.php`, since you don't win anything here compared with that option.

Let me know if you need any more help.

Stephan Stanisic

**Comment by MatthewSaintBull** [comment]
Hi,
thanks for the help. 
I want to add these things as plugins because it's easier to import in other projects. 
To do this, I've implemented a new "features" class and made the hook function public inside index.php.
I know that I could do this adding inside the theme file, but if I want to use a new theme, I need tomove the code in *every* single theme that I use. 
If there isn't any way to do this as clean as possible, I think I'll use the current way I'm using and refactor every time the index file when it's updated. 
Thanks,

Matteo.

**Comment by robiso** [comment]
@MatthewSaintBull, if I understand correctly, all you need is a hook for the block() (subside) contents?

Like currently, in 2.7.0, we support something like this:
`wCMS::addListener('footer', 'yourFunctionName');`

All you would need is something like an addListener to the blocks() section?
- Blocks are the subside and other static blocks.

**Comment by StephanStanisic** [comment]
As far as I know WonderCMS doesn't support attaching hooks to content block.

In WonderCMS 3.0.0 (that's in the branch experimental-3.0.0) all of WonderCMS' functions are public, so the `hook` function is also public there.
Maybe that is something that will solve your problem here?

Also, if the features class would extend WonderCMS, you wouldn't have the problem that the index.php file will get overwritten in updates. You'll just need to change the directory index to the extended file. E.g. with apache:
```
DirectoryIndex feature.php
```

**Comment by robiso** [comment]
@StephanStanisic, yeah I mean't in this case we could add a hook in the experimental 3.0.0.
But is it really necessary if it can be solved with extending?

**Comment by MatthewSaintBull** [comment]
> As far as I know WonderCMS doesn't support attaching hooks to content blocks.
> 
> In WonderCMS 3.0.0 (that's in the branch experimental-3.0.0) all of WonderCMS' functions are public, so the `hook` function is also public there.
> Maybe that is something that will solve your problem here?
> 
> Also, if the features class would extend WonderCMS, you wouldn't have the problem that the index.php file will get overwritten in updates. You'll just need to change the directory index to the extended file. E.g. with apache:
> 
> ```
> DirectoryIndex feature.php
> ```

Yes, This will solve the problem. 
Thanks a lot,

Matteo.
