### ISSUE TITLE
WonderCMS 3.0.1 beta released - download + UPDATE

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#163]
# WonderCMS 3.0.1 beta released  🚀
After months of hard work and refactoring, we are finally able to release version 3.0.0.
New features will make editing your websites and building things even more fun.

**Enjoy this small, powerful and ultra fast CMS!**

### **[WonderCMS-3.0.1-beta.zip](https://github.com/robiso/wondercms/releases/download/3.0.1beta/WonderCMS-3.0.1-BETA.zip)**
  - 3.x.x beta repository: https://github.com/robiso/wondercms/tree/experimental3.0.0
  - 3.0.1 beta release: https://github.com/robiso/wondercms/releases/tag/3.0.1beta

## New features
- Speed improvements.
- Built in theme and plugin installer - inspired by Stephan Stanisic.
- Caching/update system for fetching themes and plugins.
- Default page can be now selected from drop down.
- More notifications and shortcuts to opening specific tabs in the Settings panel.
- Major code clean up and optimization. Special thanks to Slaven Stančič.
- Improved updating system for WonderCMS core.
- Numerous bug fixes.
- WonderCMS 3.0.0 and above requires **PHP version 7.2** or higher.

## New themes
- Fallout by Turboblack
- Parallax by Stephan Stanisic
- Carbide by Carbide

## New plugins
- Simple blog by Stephan Stanisic
- Summernote air editor by Stephan Stanisic

## Updates
You will normally receive beta updates through the one click updater. Once we are ready for a stable release, your beta version will be upgradable to 3.0.0 stable.

## Migration
Easiest way to migrate from 2.7.0 is to manually copy/enter your pages and menu items.

# Special thanks
Without you, WonderCMS 3.0.0 would not be as amazing. Thank you for all the effort!
- Slaven Stančič (for all the code re-writing, implementation, genius on the spot programming and fixing most all the plugin issues)
- Stephan Stanisic (for the inspiration, new ideas, plugins, themes, helping out with user support and bringing so much excitement to the project!)
- Nicolas Carpi (for re-writing a mayor part of WonderCMS)
- Anusya Angamuthu (for reporting vulnerabilities)
- Turboblack (for the themes and promoting WonderCMS in other markets)

**Comment by NicolasCARPi** [comment]
Hello Robiso,

Congrats on publishing the beta! I tried it quickly (because that's what beta are for, right?), and here are a few thoughts that you might find good to know:

* it should be made clear that the whole folder needs to be writeable by the web server user. The one step install should in fact be two steps, and the second is `sudo chmod -R www-data:www-data wondercms`. Or if you want to keep it 1 step, you should add a check to see if the directory is writeable before trying to mkdir, and display an informative error to the user (currently it's a white page and one has to go in the logs to find out what didn't work). This is very easy to add to the code and improves a lot the user experience! ;)

EDIT: just saw the `checkFolder()` function, I think it should throw an exception instead of `alert()` because user doesn't get a chance to see the alert!

* kind of the same issue: at first I only chmoded without the recursive flag, so the theme folder was not writeable, and then I tried to download another theme, and it showed me the success message, even though it wasn't capable to do [this line](https://github.com/robiso/wondercms/blob/3.0.0beta/index.php#L979). That's because the return value of the rename function is not checked (and also because there is no check that the folder is writeable).

* after install one has to change the loginUrl, so I thought that it would be best if that slug was autogenerated (same as the password). Because we all know a lot of users will not change this value, if it's random by default, it's much better!

Cheers,
~Nico

**Comment by robiso** [comment]
Hi @NicolasCARPi.

We'll add the exception and the additional writable folder check on the theme plugin installer.

In regards to the login URL - the "change your login URL" warning message persists until the user changes it. Hopefully this is enough incentive for the admin to change the actual login URL and actually bookmark/save it somewhere and doesn't lock themself out of logging in (as we hide the login URL from the footer once the user changes it).

Thanks for taking it for a spin and the feedback.

**Comment by StephanStanisic** [comment]
So something that may be handy for the admin:

When the list of plugins/themes get's updated, the admin experiences a slow pageload (like on login)

I think that a better solution would be to send the page first, then update the plugins/themes like so:

```
ignore_user_abort(true);
set_time_limit(0);
ob_start();

// do initial processing here

echo $response; // send the response
header('Connection: close');
header('Content-Length: '.ob_get_length());
ob_end_flush();
ob_flush();
flush();

// now the request is sent to the browser, but the script is still running
// so, you can continue...
```
From [stackoverflow](https://stackoverflow.com/questions/15273570/continue-processing-php-after-sending-http-response)

**Comment by robiso** [comment]
@StephanStanisic, the above wasn't included due to other issues that arise when choosing such a way: sometimes the themes/plugins area isn't populated in the settings panel if the cache isn't done checking.

We've added a loader which shows the admin that updates are being fetched which is much better than waiting at a screen and thinking the page is slow.

**Comment by robiso** [comment]
@NicolasCARPi, those fixes (exceptions and check writable folders) are now added. Thanks for the feedback.

# WonderCMS 3.0.1 beta released

**Comment by 2nlin3** [comment]
Отличная новость! Благодарю всем программистам!

**Comment by robiso** [comment]
Closing issue, stable 3.0.4 released. :)
