### ISSUE TITLE
Web Page Empty On Install

### ISSUE THREAD

**Issue by bmherard** [robiso/wondercms#183]
This is an active discussion on the community forum (https://www.wondercms.com/forum/viewtopic.php?f=45&t=1264). Some how on install the "homepage" is rendering blank even when the minimum system requirements are in place.

**Comment by slavenstancic** [comment]
@bmherard can you please past your .htaccess settings?

**Comment by bmherard** [comment]
@slavenstancic  It doesn't have anything to do with the .htaccess. Another user determined that the default them is corrupt. It works using a different theme. `https://github.com/StephanStanisic/_empty` was the recommend theme to get up and running. That solution worked.

**Comment by robiso** [comment]
@bmherard, me and Slaven talked about this briefly and it seemed it could be one of the options.

I briefly checked what's the difference between the default theme and other themes: it's using a PHP short tag `<?` instead of the full `<?php`

Your server seems to have the short tag disabled (and are usually enabled by default: https://stackoverflow.com/questions/2185320/how-to-enable-php-short-tags)

**I've pushed the fix for the default theme. Please login to your website and click "Check for updates" in the Settings panel, and an update for the default theme will be shown.**

**Comment by robiso** [comment]
Closing issue and update for default theme deployed.

**Login to your website and click "Check for updates" in the Settings panel, and an update for the default theme will be shown.**
