### ISSUE TITLE
pagename that ends with a questionmark

### ISSUE THREAD

**Issue by kroovysteph** [robiso/wondercms#19]
@robiso
in the menu bar at the top, if you have a pagename that ends with a questionmark then the highlighting doesn't work anymore.

**my setup:**
`Server version: Apache/2.4.18 (Ubuntu)`

**example:**
in the following example, if you click on "FRAGEN?" it will not highlight as it is supposed to do.

<img src="https://screenshots.kroovy.de/2017-01-29_104826_screenshot.png">

should be easy to reproduce and hopefully easy to solve.

kind regards
kroovy

**Comment by robiso** [comment]
@kroovysteph 
I'll explain on how this is possible, but first why I would not recommended doing this.
In general, items in the menu are not supposed to include special characters.
WonderCMS without .htaccess would write URLs like http://example.com/index.php?page=pageName. With the help of a simple rewrite rule **RewriteRule ^(.+)$ index.php?page=$1 [QSA,L]**, we replace that part by just delivering http://example.com/pageName.
Because of the QSA parameter, a query string is passed with the original URL and is appended to rewrite it in a way that your URL pageName?param=1 becomes index.php?pageName&param=1, thus rendering it incorrectly (notice the ? -> &).

One way of making this work would be:
1. Removing the rewrite line from .htaccess, but by doing this - clean URL's will no longer be working.
2. Edit menu to include index.php?page= in your menu links.
3. You will be able to have question marks in your menu links, they'll be also highlighted. For example, your URL would be http://example.com/index.php?page=yourpage? (and highlighted).

**Comment by kroovysteph** [comment]
ah, you are right!
knowing that I would prefer clear URL's...
thank you!
