### ISSUE TITLE
[Plugin request] Simple local CDN for all scripts

### ISSUE THREAD

**Issue by RarogCmex** [robiso/wondercms#194]
Ok, for purpose of fast performance and reliability there are reasons to distribute all critical scripts such as https://code.jquery.com/jquery-1.12.4.min.js from one webserver.
Despite wondercms by concept is lightweight solution and can't handle extra scripts, however, why just do not create plugin that includes all key CDNed resources like jquery-1.12.4.min.js?

**Comment by StephanStanisic** [comment]
I am not sure what you mean, the scripts from WonderCMS are loaded via a CDN. This should give the best speeds, because networks like these are huge and can handle high loads. For people connecting to the server from afar this is also good, because there will probably be an CDN server close.

If you are asking _why_ libraries like jQuery are used, well, I have no good answer for that. The logic for the admin panel is quite simple and could be rewritten in vanilla js. Would take quite some effort to do, in order to make sure the admin panel is backwards compatible with older ECMAScript versions.

**Comment by RarogCmex** [comment]
> the scripts from WonderCMS are loaded via a CDN

Ok, can I replace remote CDN for my own local ones?

**Comment by StephanStanisic** [comment]
You'd have to edit the themes in order to load the scripts/styles locally. As for the admin scripts (these are also loaded via a CDN), you'd have to do a find/replace using a plugin (if the script is available during the hook time). 

Something along the lines of:

```php
$Wcms->addListener("js", function($args){
    $args[0] = str_replace("old_url", $Wcms->url("path_to_script"), $args[0]);
    return $args;
});
```
(Haven't tested this, may or may not work)

If the admin js isn't available during plugin hook time, you'd have to edit `index.php`. You will lose changes on update, so what you maybe can do is extend the Wcms class in a new file.

If you create `updates.php` and in there overwrite the correct variables/functions and initialise WonderCMS with your extended class you now have the changes there. Only thing is to update `.htaccess` to use the `updates.php` file instead of the `index.php` file.

**Comment by robiso** [comment]
Closing issue, please feel free to continue the discussion.
