### ISSUE TITLE
[Plugin upgrade request] - Contact form captcha

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#207]
There have been a couple of requests in regards to adding captcha to either contact form plugins:
https://github.com/robiso/contact-form/issues/4

@StephanStanisic also created an alternative contact form, it might make more sense to include the captcha on that plugin: https://github.com/StephanStanisic/contactform once the delivery issue is figured out.

Any help is appreciated.

**Comment by StephanStanisic** [comment]
I have used https://captcheck.netsyms.com/ sucessfully in order to fight bots. It's open source, and we could bundle it in the plugin.

There are also some alternatives on this website: https://switching.software/replace/google-recaptcha/

After I figure out the problems with the delivery of contactform, I'll take a look at a captcha.

**Comment by gppixelworks** [comment]
I'd like to use **[hCaptcha](https://www.hcaptcha.com/)** with this plugin.  All that need be added are the following two lines to the web form:

```
<script src="https://js.hcaptcha.com/1/api.js" async defer></script>
<div class="h-captcha" data-sitekey="xxxxx"></div>
```

Any thoughts on how to integrate this?

**Comment by robiso** [comment]
@gakowalski where in contact-form.php did you do the changes?

**It seems starting with line 189 would be the correct lines to put this in.**

**Comment by gakowalski** [comment]
@robiso never changed anything in this file

**Comment by robiso** [comment]
Sorry @gakowalski , tagged the wrong person :)

@gppixelworks, please read my previous post to see where you have to add the hCaptcha.
