### ISSUE TITLE
[Bug] database.js getting overwritten with 0 bytes

### ISSUE THREAD

**Issue by StephanStanisic** [robiso/wondercms#208]
As discussed on the support forum, a few users (myself included) have had an issue where the database file has no contents. 

I am unsure what is causing the database file to empty out, but this is a big problem since the following user didn't have any plugins installed.

https://www.wondercms.com/community/viewtopic.php?f=45&t=1401

This is definitely a issue we need to tackle together, without a way to reproduce this will be really hard to debug.

So, first things first: How can we reproduce this issue?

**Comment by robiso** [comment]
Hopefully @slavenstancic pull request will fix this issue and prevent it from happening again.
The pending pull request will be merged once we confirm the report security issues have been fixed (https://sec-consult.com/en/blog/advisories/multiple-vulnerabilities-in-wondercms/).

@StephanStanisic I couldn't reproduce this again, so hopefully someone gets lucky and finds a repeatable way of reproducing it so we can indeed confirm it was fixed.

Thanks for the report!

**Comment by StephanStanisic** [comment]
I am not sure who reported this, https://sec-consult.com/en/blog/advisories/multiple-vulnerabilities-in-wondercms/, but it seems all to have to do with the authenticated user. Since this user can already upload arbitrary files I am not sure how much of a 'security problem' this is.

The emptying of the database.js is a big issue tho.

**Comment by robiso** [comment]
@StephanStanisic the vulnerabilities can be serious if the user is tricked into uploading a shell or if a shared hosting isn't isolating the users properly. I agree they're not nearly as critical if they didn't require logging in.

In regards to the database, this update should provide a fix, since we now lock the database while it's open/being written into. If we find a way to reproduce the corrupted database, we can surely verify it with this fix. I still haven't managed to find a way to reproduce this issue. Could it be a GitHub outage or something that closes down the database.js request and possibly writes an empty one instead of the actual content?

**Comment by robiso** [comment]
Closing issue, pull request merged. Thanks everyone!

**Comment by robiso** [comment]
Re-opening, seems to be still an issue:
https://www.wondercms.com/community/viewtopic.php?f=45&p=2942#p2942

**Comment by zenull** [comment]
Great CMS overall but the issue is very serious. It just wipes the database..
Is the any way to disable update/CURL to Github at all?
Would be great to disable this temporary till debugging..

Thanks!

**Comment by robiso** [comment]
@zenull we're still trying to work this out and find some steps to reproduce.
Hopefully we'll be pushing a fix out this week, but it seems like playing minesweeper, since we have to push an update to see if it fixes the issue (since we can't reproduce it fully yet).

Thanks for the support, if there's any way you can think of helping to debug, please do. 🤞

**Comment by robiso** [comment]
@zenull @StephanStanisic @slavenstancic 
hopefully the debugging turned on in the latest release 3.1.2 will completely prevent any database corruption and enable us to review error logs that will be generated if any issues arise.

Will keep this thread open for future debugging sessions.

**Comment by robiso** [comment]
@zenull this shouldn't be repeating anymore since 3.1.2 (released about a week ago) or 3.1.3 released today.

However, if you check your /data/ folder, there should be a logs file explanining what the issue was. Please note logs will only shopw up in 3.1.2 and onwards (so if you haven't updated, please update to 3.1.2/3.1.3 and wait for any logs to come up after some usage).

Hopefully, error logs will help us pinpoint where the issue is (without overwriting/wiping the database).

**Comment by robiso** [comment]
Closing issue since we now have a failsafe in place and let's keep it there to prevent any DB corruptions in the future.

If anyone manages to get something in their data/logs, please post them here.
