### ISSUE TITLE
[Feature request] Caddy web server support

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#216]
Requested: https://www.wondercms.com/community/viewtopic.php?f=45&t=1555

**Comment by Prophet-Phoenix** [comment]
Hi there,
i tried getting wondercms to work with caddy server and PHP 7.4. My Caddy(config)file is:
```
example.com {
  root * /var/www/wondercms
  file_server

  respond /cache.json 403
  respond /database.js 403

  try_files {path} {path}/ /index.php?page={http.request.orig_uri.path.file}

  php_fastcgi unix//var/run/php/php7.4-fpm.sock
  }
```
This is basically the nginx config file given in your wiki. Generally i got wondercms working this way, but it has a few quirks:
- Logout of admin is not able because the logout redirects to `example.com/logout**&**token=sometoken` instead of `example.com/logout**?**token=sometoken`. It seems that wondercms does not recognise the internally rewritten url `/index.php?page=logout` and appends only `&token` to the url. But at that time the actual URL in the browser bar reads `/logout` so it should append `?token=`, right? Or is this some caddyserver issue? I already asked [there](https://caddy.community/t/caddy-v2-with-wondercms/15302).
- Some plugins do not install from web ui. Maybe related to first issue. Couldn't debug.

Greetings

**Comment by francislavoie** [comment]
The problem is with this line:

https://github.com/robiso/wondercms/blob/506b0385ebd5e979b5c8cec255d215816789416f/index.php#L2154

It's not valid to use `&` as the start of a URL query. This should be changed to `logout?token`.

**Comment by francislavoie** [comment]
Also FWIW, relying on a `page` query for routing is not good. All modern PHP frameworks use `$_SERVER['REQUEST_URI']` and route based on that value. This is the original request path as sent by the browser. For a simple example, take a look at how it's done here: https://github.com/nikic/FastRoute#usage. Doing it this way, server configs become _much_ simpler because it avoids having to do rewrites to set the `page` query, and servers can essentially just pass through the request to PHP over FastCGI.

**Comment by robiso** [comment]
This should be addressed with the next version.

Thank you @francislavoie, @robertrud and @Prophet-Phoenix

**Comment by robertrud** [comment]
Nice! I'm looking forward to it.

**Comment by robiso** [comment]
@robertrud , @francislavoie, @Prophet-Phoenix.

We have now added a Caddy web server support doc: https://github.com/robiso/wondercms/wiki/Caddy-web-server-config along with a new version of WonderCMS 3.3.2, which has the logout parameter fixed.

I would like to thank everyone in the thread for their contributions and would love to list all of you on our official contributors page: https://wondercms.com/contributors.

Please provide
- first/last name (or nickname)
- link to your website

Closing this issue, please feel free to reopen it or comment any additional improvements.
