### ISSUE TITLE
Improve theme/plugin caching to avoid issues

### ISSUE THREAD

**Issue by robiso** [robiso/wondercms#221]
1. Main/master branch checking.
2. Check status code from theme/plugin page/repo. (terminate if 404).

**Comment by socram8888** [comment]
Hello! I've recently discovered this CMS and I'm in love in how simple yet functional it is. It took me very little time to re-do part of my website (currently generated using Jekyll, which I am honestly too lazy to edit, commit, upload, wait to compile, wait to publish) in WonderCMS, which is really awesome.

However, I've been bit by the plugin/theme updating feature. Namely, the process is so painfully slow it times out in my local test installation of XAMPP, and I have to disable it to keep make it work.

Hence, I've considered improving this process, but I'd like to hear your thoughts on what would be the best way to go forward. Currently, I had thought of the following approachs:

## Method A: move check to JavaScript

The admin page would render a stub with all known, registered plugins and themes but without any update information. This would get fetched by either JSONP or XMLHttpRequest, probably proxified using PHP to workaround CORS and to allow caching as it currently does.

This does not seem like a hard task - it'd probably require adding a new method to Wcms class, and if a certain query parameter is passed AND the user is logged in, bypass the init and render methods, perform the same check it currently does with and return a JSON(P) to the frontend to display the information.

The downside is that it might be a PITA to notify the user, as we'd need to implement logic in the frontend to trigger alerts AFTER the page has rendered, which would increase code bloat.

## Method B: add more metadata to the repository master list

Currently, the themes-list.json and plugins-list.json are not JSONs, but it'd be very helpful if they were. For instance, all the current logic implemented to see if the repo's branch is master or main, if the picture is available or not, or what version it is, could be moved to it, reducing the number of calls from three per repository to a singular one.

Such as JSON could be something along the lines of:
```
{
	format: 1,
	plugins: [
		{
			name: "Summernote Editor",
			description: "Adds an WYSIWYG editor to all content editable fields.",
			version: "3.2.1",
			preview: "https://raw.githubusercontent.com/robiso/summernote-editor/master/preview.jpg",
			installZip: "https://github.com/robiso/summernote-editor/archive/refs/heads/master.zip",
		},
	],
	themes: [
		{
			name: "Universe Gradiente",
			description: "An example theme",
			version: "x.x.x",
			preview: "https://raw.githubusercontent.com/robiso/universe-gradiente/master/preview.jpg",
			installZip: "https://github.com/robiso/universe-gradiente/archive/refs/heads/master.zip",
		},
	]
}
```

Importantly - you would __not need to manually update the list__ yourself - you could easily use an automated GitHub pipeline running daily to generate such JSON.

This would __massively improve performance__ and simplify a ton of the current WonderCMS logic for update checking.

Users, rather than adding new plugins using a raw Git repository URL, could just register new plugin/theme pointing to a file in the format above described, which could be for a singular plugin/theme if desired.

## Method C: move plugin metadata to a singular file

This is a variation of the above, but rather than having a master list, move the "summary", "description", "version", etc... into a singular JSON/YAML/whatever, which would reduce by a factor of three the number of calls required for update checking.

**Comment by robiso** [comment]
Hello @socram8888.

Thank you for your feedback and I couldn't agree more, the current caching mechanism is a bit slow.

I'd also go with version B, as this is something almost exactly that we have discussed with with @slavenstancic some time ago (he's also the creator of the current caching system).
- Not sure if you've already seen the `cache.json` file generated on first WonderCMS initialization, it gets created in the data folder. It's currently used for checking version on user server and compares them to the GitHub repositories (versions) of the themes and plugins.

@socram8888 to start this off, what would help you the most? If I prepare a sample json for proposed B solution on https://github.com/robiso/wondercms-cdn-files, would that help you out?
- For the time being we would retain `themes-list.json` and `plugins-list.json` until we would have a working version and then migrate everyone to the new list with a new WonderCMS update.

@slavenstancic would this make the current `cache.json` file in the users `data` file obsolete? It seems so to some degree.

@socram8888 thanks again for joining in and writing a very informative post with multiple solutions.
After we come to a working solution, we would like to reward you with a symbolic donation from the WonderCMS donation fund, along with an honorable mention on https://www.wondercms.com/contributors.

Let's use this thread to keep progress and reach out for help (to @slavenstancic and I) if you get stuck at any point.

**Comment by socram8888** [comment]
@robiso Oh yes, absolutely, the cache.json format is perfect. The only thing I maybe would change (if you are okay), is the key from the repository URL, to the "dirName", ie from:
```
        "https:\/\/github.com\/robiso\/summernote-editor": {
            "name": "Summernote editor",
            "dirName": "summernote-editor",
            "repo": "https:\/\/github.com\/robiso\/summernote-editor",
            "zip": "https:\/\/github.com\/robiso\/summernote-editor\/archive\/master.zip",
            "newVersion": "3.2.1",
            "image": "https:\/\/raw.githubusercontent.com\/robiso\/summernote-editor\/master\/preview.jpg",
            "readme": "Adds an WYSIWYG editor to all content editable fields.",
            "readmeUrl": "https:\/\/github.com\/robiso\/summernote-editor\/blob\/master\/README.md"
        },
```
To:
```
        "summernote-editor": {
            "name": "Summernote editor",
            "repo": "https:\/\/github.com\/robiso\/summernote-editor",
            "zip": "https:\/\/github.com\/robiso\/summernote-editor\/archive\/master.zip",
            "version": "3.2.1",
            "image": "https:\/\/raw.githubusercontent.com\/robiso\/summernote-editor\/master\/preview.jpg",
            "readme": "Adds an WYSIWYG editor to all content editable fields.",
            "readmeUrl": "https:\/\/github.com\/robiso\/summernote-editor\/blob\/master\/README.md"
        },
```
The reason is that it'd be possible to override plugin definitions in previous custom lists, for example for development purposes before creating a PR.

About the CDN example file, don't worry - I'll fork it and use it for the mean time, and I'll send you a PR on that repo once development on both this and the other are done :)

Regarding making cache.json obsolete, I'd still recommend keeping it, since we probably don't want to fetch the plugin/theme list on every page reload.

**Comment by robiso** [comment]
@socram8888 has anyone told you you're amazing in 2022 yet?

Thanks again for the feedback and it already feels like you're one of us. Glad to have you on board!
Also, agreed with everything you said (including the reasoning for keeping the cache.json).

Looking forward to an even better WCMS experience thanks to contributors like yourself. 🚀

**Comment by socram8888** [comment]
Thanks for the kind words, @robiso!

Now that the cache file is somewhat finished (see https://github.com/robiso/wondercms-cdn-files/pull/14), I'd like to also know your opinion on external plugin installation.

Currently, the process for adding external addons than those from the plugins-list.json and themes-list.json is adding the URL of a GitHub or GitLab repository, so I see the two following options:

## Option A: keep it as is

External plugins are still loaded using the "summary", "version", etc... autodiscovery that is currently implemented, while official ones use the aggregated cache format.

**Pros**:
 - We keep perfect backwards compatibility.

**Cons**:
 - The process of requesting update information for official and external plugins would be entirely different, so we'd introduce more code and it'd make harder to test.
 - We'd need to keep duplicated functionality - one in the CDN reposiroty in JavaScript to build the cache, and another in PHP for external plugins.
 - Is limited to GitHub or GitLab, due to the hardcoded discovering.
 - The slowest option. Probably not not significant unless the user has a significant amount of plugins, though.

## Option B: ask developers to provide a wms-modules.json file

We'd need to ask developers to begin shipping a wms-modules.json file with their plugins, which could be either manually built or autogenerated like we are doing.

**Pros**:
 - We could remove a considerable amount of code from PHP to remove the autoconfiguration.
 - Testing would be easy, as the same code that we use for the official plugins, would do for external ones.
 - The fastest of the two options.
 - Allows hosting projects in __any__ website, even outside GitHub or GitLab, as wms-modules.json files have all the information required to be installed.

**Cons**:
 - Breaking change - developers would need to create this new file with the information.

---

What are your opinions on this?

**Comment by robiso** [comment]
>  Now that the cache file is somewhat finished (see robiso/wondercms-cdn-files#14), I'd like to also know your opinion on external plugin installation.

Looks good!


> What are your opinions on this?
Option B seems like the most sensible solution. What do you think @socram8888 & @slavenstancic?

A few questions pop up:
1. Does the structure of the current cache.json on the users end have to change in any way? (if so, we'd have to do a migration).
2. What would the wcms-modules.json need to include, would it be as simple as providing something like
```
{
    "version": 1337,
    "plugins": {
        "summernote-editor": {
            "name": "Summernote Editor",
            "repo": "https://github.com/robiso/summernote-editor/tree/master",
            "zip": "https://github.com/robiso/summernote-editor/archive/master.zip",
            "summary": "Adds an WYSIWYG editor to all content editable fields.",
            "version": "3.2.1",
            "image": "https://raw.githubusercontent.com/robiso/summernote-editor/master/preview.jpg"
        },
    }
}
```
within their plugin/theme repository? Or is the format any different (a sample for the docs will be useful in the future)
3. Just to clarify with "autodiscovery", do you mean the way WonderCMS checks the cache.json file against all plugins and repositories and switching over to this single file (when the user logs into their WonderCMS instance)

Regarding
> developers would need to create this new file with the information.
This is not an issue in my opinion, as we currently fork all plugins/themes and they're all in a single repository, which we control, so I could simply provide the wcms-modules.json for all of them. And for new ones, I wouldn't stress too much as it only brings good things for the future.


The next of this would be:
- remove github/gitlab limitations from WonderCMS
- remove checking for all repos and check only the single wcms-modules.json
- prepare wcms-modules.json for all themes and plugins (just please correct me on the format above)

Please correct me if I'm wrong on any of the above.

Do you see any issues this being merged to the CDN repo as is? It shouldn't interfere with any of the current state that the WonderCMS users have as far as I can tell.

-----
Last but not least, how can I reach out to you? Will the email on your GitHub profile do? If you have Discord or even Signal, that would make things easier in regards to sending over a donation.

I think you've already more than earned a spot on our contributors list. Would the following be correct?
- Marcos Del Sol Vives 
- [Link to your website](https://orca.pet)

**Comment by socram8888** [comment]
I am also really in favour of option B, since it'd make things really easier.

Regarding the wcms-module.json, let me clarify a bit how the changes I want to make. Currently, the update process does the following:

![wcms-current](https://user-images.githubusercontent.com/515068/149835843-19d07ff7-e3e2-4bc9-a16a-f5288327719a.png)

The PR on the CDN repository would be a stepping stone onto changing it to the following mechanism:

![WCMS Proposed](https://user-images.githubusercontent.com/515068/149836329-f339dd65-d9c0-45dd-8b36-067d1ce813bb.png)

Importantly, the script will [use the existing themes-list.json and plugins-list.json](https://github.com/robiso/wondercms-cdn-files/blob/cb6e09ad381ef61578f42b1f75e8e80d5683e587/build-wcms-modules.js#L226-L229) files to [fetch the metadata from the repositories](https://github.com/robiso/wondercms-cdn-files/blob/cb6e09ad381ef61578f42b1f75e8e80d5683e587/build-wcms-modules.js#L165-L186) in the same format that they are currently defined.

Essentially, __it moves to GitHub actions__ the action of testing the branch name (if either main or master), the fetching of the summary, version and picture for everyone of your plugins and themes, so PHP needs to fetch only a single file to know the state of all your projects, but the __process stays the same__.

That means that, **at the moment**, you would not need to add anything or make any changes to any of your repositories, other than the CDN one to include this new file. At some point, it could be maybe helpful to merge "summary" and "version" into a single file, but that's not really needed now.

![WCMS Next](https://user-images.githubusercontent.com/515068/149837772-11298f9d-5635-4bcc-830e-78474e4c4c8a.png)

It'd maybe help to think of the modules-list.json as a Debian repository: it contains all the relevant metadata for a list of packages. This repository may be for multiple packages, but it might also contain a singular package.

Thus, external developers would need to write said repository file, which could be done on a per-repository basis (one wcms-modules.json file per project), or use some mechanism to aggregate all their projects into a singular one (like the new CDN script does)

```
{
    "version": 1,
    "plugins": {
        "summernote-editor": {
            "name": "Summernote Editor",
            "repo": "https://github.com/robiso/summernote-editor/tree/master",
            "zip": "https://github.com/robiso/summernote-editor/archive/master.zip",
            "summary": "Adds an WYSIWYG editor to all content editable fields.",
            "version": "3.2.1",
            "image": "https://raw.githubusercontent.com/robiso/summernote-editor/master/preview.jpg"
        },
    }
}
```

Would be indeed a basic wcms-module.json file an external developer could use for a single project. Note the outer "version" must be set to 1, as this is to detect if the metadata is in a format we understand.

> 3. Just to clarify with "autodiscovery", do you mean the way WonderCMS checks the cache.json file against all plugins and repositories and switching over to this single file (when the user logs into their WonderCMS instance)

The cache.json would indeed need to be wiped, but that shouldn't be a problem, as there's no data that should persist in that file, no?

> Do you see any issues this being merged to the CDN repo as is? It shouldn't interfere with any of the current state that the WonderCMS users have as far as I can tell.

Correct, this introduces a new file but nothing else needs to change on that or any other of the repositories.

> Last but not least, how can I reach out to you? Will the email on your GitHub profile do? If you have Discord or even Signal, that would make things easier in regards to sending over a donation.

There's really no need for a donation. I was planning on donating to you for your work on maintaining this project so consider this even :)

> I think you've already more than earned a spot on our contributors list. Would the following be correct?

Yup, that's all correct!

**Comment by robiso** [comment]
> Regarding the wcms-module.json, let me clarify a bit how the changes I want to make. Currently, the update process does the following:

@socram8888 thank you for the very clear diagram. I'll make sure to add this to the wiki after we go live with the new version.

> It'd maybe help to think of the modules-list.json as a Debian repository: it contains all the relevant metadata for a list of packages. This repository may be for multiple packages, but it might also contain a singular package.

> Thus, external developers would need to write said repository file, which could be done on a per-repository basis (one wcms-modules.json file per project), or use some mechanism to aggregate all their projects into a singular one (like the new CDN script does)

Additional question here, if a plugin/theme repository author wants to push an update to their plugin/theme, do they still only have to bump the `version` file, or do they have to bump it in the wcms-modules.json as well (or only wcms-modules.json)? Just want to clarify if any of the author repository file become irrelevant?
- This is how it currently works, once they bump the version and a WCMS instance checks the repos, if the version on the GitHub/Gitlab repository is higher, it will show the "update" dialog.


> The cache.json would indeed need to be wiped, but that shouldn't be a problem, as there's no data that should persist in that file, no?
Correct, we can delete the cache.json file with the next update, it re-creates itself if it doesn't exist.
I'll have to check what happens with the defaultRepos in the main database.json file and what role it has (it was done some time ago and I'm pretty rusty).


> There's really no need for a donation. I was planning on donating to you for your work on maintaining this project so consider this even :)

How hard do we have to convince you? We'd just like to reward and in a dream world would love to have you as a contributor on the team since you're a wizard (without any obligations). Added you to: https://www.wondercms.com/contributors. If you persist on the donation (hopefully not), at least pick something from the store: https://swag.wondercms.com/ and we'll send it over along with free shipping.

I've went ahead and merged your changes. Next, I'll be creating all the wcms-modules.json for each of the current repositories.

@socram8888 thank you!

**Comment by socram8888** [comment]
> Additional question here, if a plugin/theme repository author wants to push an update to their plugin/theme, do they still only have to bump the `version` file, or do they have to bump it in the wcms-modules.json as well (or only wcms-modules.json)? Just want to clarify if any of the author repository file become irrelevant?

They'd need to edit only the wcms-modules.json. They might still want to keep at their discretion the other two files if they want to be useable by older versions of WonderCMS, since this will break how the installation works but not anything API-related.

> * It currently seems from my understanding that this will still be used and be picked up by the Github actions once it skims through all the repos.

Yes, that is correct.

Just to be more clear: the WonderCMS will only care about the information in wcms-modules.json. How this file is generated is not WonderCMS' business: it can be generated either by aggregating other wcms-modules.json, by reading version/summary/picture.jpg files, or just manually if a developer chooses so.

> I've went ahead and merged your changes. Next, I'll be creating all the wcms-modules.json for each of the current repositories.

The script is currently not capable of using wcms-modules.json from repositories linked in the (themes|plugins)-list.json files, but only reading version/summary files to aggregate them. Will work on that ability to aggregate them later.

**Comment by robiso** [comment]
> Just to be more clear: the WonderCMS will only care about the information in wcms-modules.json. How this file is generated is not WonderCMS' business: it can be generated either by aggregating other wcms-modules.json, by reading version/summary/picture.jpg files, or just manually if a developer chooses so.

Completely clear now, the "new" way will be plugin/theme authors bumping the version in the wcms-modules.json file, thus triggering the update for all users once their servers fetch the new wcms-modules.json from the CDN and retaining old summary/version for compatibility reasons for some time.


> The script is currently not capable of using wcms-modules.json from repositories linked in the (themes|plugins)-list.json files, but only reading version/summary files to aggregate them. Will work on that ability to aggregate them later.
I completely understand that, but it seemed "smart" to prepare all the wcms-modules.json files on all theme/plugin repositories beforehand (even if they don't serve any function for now)?

The next step right now is for me and @slavenstancic to jump on a coding call over the weekend and start digging into the new version of WonderCMS.

To do (please feel free to add, might of missed something.)
- remove github/gitlab limitations from WonderCMS
- remove checking for all repos and check only the single wcms-modules.json from the CDN
- wcms.modules.json file on all theme/plugin repositories
- wipe the cache.json with the next update so it fetches all latest values

**Comment by robiso** [comment]
@socram8888 thank for the aggregation pushes to the repository, awesome work.

I've just finished creating `wcms-modules.json` for all themes and plugins - except for two themes, as I have a question.
1. What would happen if I forked these two themes below?
- https://github.com/StephanStanisic/theme-w3css-singlepage
- https://github.com/StephanStanisic/watercolor
and replaced the repository URL to `robiso/watercolor` in the `themes-list.json`?
Would users themes linked to the old repository suddenly have duplicates in their Settings list?

2. Can we somehow remove/trim the `\n` (breaks) in the main `wcms-modules.json` file?
- I've currently manually removed breaks from their respective summary files and also removed `\n` from the `wcms-modules.json` when uploading to their repositories.
- I would just like to avoid `\n` being printed in the Settings while users are logged in, but this is absolutely not a big issue.

We have a scheduled programming call tomorrow with @slavenstancic , where we can attend to implementing these changes.

**Comment by socram8888** [comment]
> 1. What would happen if I forked these two themes below?
> 
> * https://github.com/StephanStanisic/theme-w3css-singlepage
> * https://github.com/StephanStanisic/watercolor
>   and replaced the repository URL to `robiso/watercolor` in the `themes-list.json`?
>   Would users themes linked to the old repository suddenly have duplicates in their Settings list?

No they would not. The wcms-modules.json uses the repository name as the key for the metadata, not the URL as it used to. So you can specify any URL as long as the module name stays the same.

In the case two wcms-modules.json specified the same module name, the last one would have priority.

> 2. Can we somehow remove/trim the `\n` (breaks) in the main `wcms-modules.json` file?
> 
> * I've currently manually removed breaks from their respective summary files and also removed `\n` from the `wcms-modules.json` when uploading to their repositories.
> * I would just like to avoid `\n` being printed in the Settings while users are logged in, but this is absolutely not a big issue.

I don't understand this part. Which newlines?
![image](https://user-images.githubusercontent.com/515068/150639063-7565f819-0e7d-47d0-952f-3a84d42b7c62.png)
None of the summary fields have new lines in them.

**Comment by robiso** [comment]
> No they would not. The wcms-modules.json uses the repository name as the key for the metadata, not the URL as it used to. So you can specify any URL as long as the module name stays the same.
Amazing, thank you! I'll fork those themes and add the wcms-modules.json (the last two missing ones).

Examples of the two themes where I manually removed them from their original repositories and their wcms-modules.json file.
<img width="792" alt="Screenshot 2022-01-22 at 13 48 34" src="https://user-images.githubusercontent.com/6200139/150639152-7b54eb07-ce5c-4e2a-89c8-4d4f97ee6f44.png">

**Comment by socram8888** [comment]
Oh those. They'll get converted back to a newline when you deserialize it from the PHP side. They won't see the "\n" sequence but an actual line break, just like they do right now with the "summary" file.

**Comment by robiso** [comment]
@socram8888 makes sense, thanks for elaborating. 

And a serious shout out to you for tackling this and greatly improving the user experience - in the name of all WCMS users - thank you!

**Comment by robiso** [comment]
@socram8888 the new caching system is implemented on this branch: https://github.com/robiso/wondercms/tree/330
Feel free to give it a go, it takes less than a second for all updates to be checked which is amazing and I'd like to thank you again for pushing this far.

Any opinion on the changes are welcome:
- https://github.com/robiso/wondercms/commit/ad602f7edf2716a907cf47e3187c2743f9d746c8

Notable differences from the original discussion above:
1. Instead of wiping the cache.json, we're simply creating a new file called wcms-modules.json, which is copied over directly from the CDN.
- I'm not completely satisfied with this solution, since it leaves the cache.json file behind and is basically useless, so I would additionally just delete any traces of this file.
- Would you suggest (while updating), we delete the cache.json file and retain the name instead of using wcms-modules.json?

2. Additionally, for custom modules, a custom-modules.json file is created. I'm really interested on your opinion on this matter.

**Comment by socram8888** [comment]
My original idea really was to keep the cache.json file, and generate it using the wcms-modules.json from all repositories (both the official and the custom), so it's super easy to iterate later through them.

Essentially what I would've done is:
 - Create a base structure for aggregation with empty arrays of themes and plugins
 - Iterate through all plugin repos (first official, then custom)
 - For each one, check if metadata version is 1. If not, either ignore or report an error
 - Copy the contents of themes and plugins into the aggregated structure

Then serialize that into the cache.json, alongside any relevant metadata you might need (such as expiration)

Maybe I missed it but I don't see such aggregation being done. If an user has multiple custom repos, wouldn't the last custom metadata overwrite all previously fetched ones?

**Comment by robiso** [comment]
@socram8888, Slaven had another programming session and fixed all of your points.
- removed the wcms-module.json and custom-modules.json and it's now merged into the single cache.json file and it used as you described - generated using the wcms-modules.json from all repositories,
- WCMS now iterates all modules and parses their wcms-modules.json data (first official, then custom),
- the metadata is checked for version being 1 (returns error "The wcms-modules.json version is incorrect") if the version is not matching,
- the themes and plugins are copied into the aggregated structure.

If anyone has had custom modules previously added (but not installed), they will not be visible in the themes and plugins section of the WonderCMS settings. These modules can however be re-added if they contain the correct structure.
- If the custom module was installed, user will still not see it in the Themes/Plugins, but the module will still work (though invisible at this stage in the settings).
 - I'll add a note to the release changelog mentioning this (and link to docs that include the required wcms-modules.json specifications).

The notable changes are here:
- https://github.com/robiso/wondercms/pull/250/commits/f94a7de279b98fa39f4be3dd9777b840349147aa
- Full pull request with additional cleanups: https://github.com/robiso/wondercms/pull/250

Thanks again for your feedback and also @slavenstancic great work done.

**Comment by socram8888** [comment]
Awesome. Thank you too!

**Comment by robiso** [comment]
Since WonderCMS 3.3.0 was published moments ago, I'm thrilled to close this issue after more than a year of it being open.

This wouldn't have been possible without you @socram8888 and there's no words to express how much you've improved WonderCMS - thank you again.

You have both been mentioned on the official release notes
- https://www.wondercms.com/news
- https://github.com/robiso/wondercms/releases/tag/3.3.0

Looking forward to future ventures and hope you stick around @socram8888. 🍺

**Comment by socram8888** [comment]
Awesome, thank you too!
