### ISSUE TITLE
Korean translation completed

### ISSUE THREAD

**Issue by nubihub** [robiso/wondercms#234]
Check this repository plz
https://github.com/nubihub/translation-korean

![applied_on_my_site](https://user-images.githubusercontent.com/80185939/112797288-25517b80-90a6-11eb-9331-8bb240a97d79.JPG)

Thank u

**Comment by robiso** [comment]
@nubihub thank you for your contribution.
I have reviewed your plugin and it works as expected, but found a bug when adding it.

This plugin will be added as soon as this bug is fixed: 
https://github.com/robiso/wondercms/issues/235

**Comment by nubihub** [comment]
@robiso I changed it to master now.
Thank you for your effort :3

**Comment by robiso** [comment]
@nubihub your plugin has now been added to the official list of plugins.
Thank you for your contribution, please let me know if it works for you as expected.

Since you're now an official contributor, send over your first and last name + website (or social media), so we can add it to our list of contributors here: https://wondercms.com/contributors

**Comment by nubihub** [comment]
'Nubi Lee' for name and my github for website please.
https://github.com/nubihub

Btw, I think it has problem with opening zip file.
When I try to install the plugin, following message shows up.
'Error opening ZIP file.'

Thank you.
