### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by jin146** [robiso/wondercms#245]
Hello, I have this issue on a freshly unzipped and uploaded 3.2.0 version of Wondercms

 `Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/wondercms/index.php on line 21`

Here is the concerned line on index.php 

`private const THEMES_DIR = 'themes';`

**Comment by robiso** [comment]
Hello @jin146, this happens if you have PHP version 7.1 or later.

WonderCMS minimum requirements have been 7.2 or later for quite some time now, and can be found here:
- https://www.wondercms.com/requirements

Closing issue. If you need any more help, please continue commenting in this issue thread.
