### ISSUE TITLE
Dom-Changing Javascript in the editor is instantly executed

### ISSUE THREAD

**Issue by dwrl** [robiso/wondercms#254]
As the title says, entering e.x.:

```
<link rel="stylesheet" href="https://cdn.plyr.io/1.6.16/plyr.css">
<script src="https://cdn.plyr.io/1.6.16/plyr.js"></script>
<script>plyr.setup(document.querySelectorAll('.js-plyr'), {});</script>

<div class="js-plyr">
  <audio controls="" crossorigin="">
    <source src="/data/files/daniel_grau-worte.mp3" type="audio/mp3">
  </audio>
</div>
```

will result in execution of the script, changing the page html and saving said page with all the player elements as put in by the javascript.

**Comment by robiso** [comment]
@dwrl, JavaScript will always be executed when put in an editable field, this has always been the expected behavior.

I would suggest manually including this script in your `theme.php`, that way it it will always be included without any changes made while editing.

Closing issue as this isn't a bug, but you can continue the discussion and will gladly answer any questions.

**Comment by dwrl** [comment]
@robiso, thank you for the fast and friendly reply ;)

Honestly it can be rather nifty to have it that way, it was just unexpected to _me_, which made my gears turn about probable security ramifications this might have on a unsuspecting user. Maybe I should have spent more time with the docs...

All the best :D

**Comment by robiso** [comment]
@dwrl most welcome :) 

The dangers of pasting random JS code or malicious SVGs are outlined in the wiki indeed: https://github.com/robiso/wondercms/wiki/, but we cant always expect everyone to be reading through documentation so a question like this definitely doesn't work.
