### ISSUE TITLE
Your WonderCMS version is out of date

### ISSUE THREAD

**Issue by halojoy** [robiso/wondercms#33]
I get this message when starting admin.
Now, my index file has '2.0.6'
and the file 'version' I have edited to have '2.0.6.'

But still I get 'Your WonderCMS version is out of date.'
Where is this problem coming from?

The message disappear when I have worked a while in the admin.

**Comment by halojoy** [comment]
I solved this:
Change is in _getOfficialVersion()

	private static function _getOfficialVersion() {
		$data = trim(file_get_contents( 'https://raw.githubusercontent.com/robiso/wondercms/master/version' ));
		return $data;
	}

**Comment by robiso** [comment]
Hello @halojoy, WonderCMS uses cURL since version 2.0.6 instead of file_get_conents. cURL enables us more options and is more flexible for fetching files from GitHub.

Using file_get_contents caused the same issue for some users.
Please ensure your host has cURL enabled on your hosting package and this problem should be fixed without editing the index.php.

**Comment by halojoy** [comment]
I had checked I have CURL.
So this is not the issue.

The problem is that 'curl'-function = _getExternalFile(()
It does return a blank.
So the program thinks I have not correct version.

**Comment by robiso** [comment]
@halojoy thanks for the additional report.

@Alamantus can you please weigh in on this? Seems better to revert to file_get_contents or should we find an alternative solution?

**Comment by halojoy** [comment]
@robiso 

I solved the problem with the CURL function.

Added this option to the function:
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

When is set to false the CURL does not check for SSL certificate.
It turns out the certificate is no good on my machine.

I run wondercms from my PC,localhost. Where I have now PHP 7.1.2, Apache 2.4.

**Comment by robiso** [comment]
@halojoy thank you. Can we make a short discussion if we should turn off SSL peer verifying by default in WonderCMS?

**Comment by Alamantus** [comment]
It might be worth it to turn it off, simply because it's for checking the update version... but I don't know how important security is for that.

_Technically_ if someone was targeting someone at the exact time of update, they could inject an infected version of the upgraded file, but I don't know how reasonable it is to worry about that... then again, I don't know much about internet security. :P

**Comment by halojoy** [comment]
I downloaded a certificate from the cURL website.
_cacert.pem_
So now it works alright.
There is no need to change in your index.php

**Comment by robiso** [comment]
@Alamantus thank you for your input. This indeed does allow for MITM attacks and like @halojoy said, download a certificate solves this. Checked the manual and comments - disabling verification of the peer is considered generally unsafe http://php.net/manual/en/function.curl-setopt.php. The pull request will be disregarded.

Thanks to both again. Closing issue.
