### ISSUE TITLE
Stored XSS in wondercms [WORKS ONLY IF ADMIN IS ATTACKER]

### ISSUE THREAD

**Issue by eidelweiss** [robiso/wondercms#38]
Hello Team,

i found a vulnerability (stored cross site scripting) and already sent email to  info@wondercms.com, this vulnerability is confirmed in last version of wondercms. and work with all modern browser. hope you can fix it asap.

Best Regards,

**Comment by robiso** [comment]
hello @eidelweiss, please see this closed issue: https://github.com/robiso/wondercms/issues/27
In short, this is wanted behaviour. An XSS vulnerability is when an **attacker** can exploit this - which is only a logged in WonderCMS user/admin. WonderCMS installations are not usually public, so if the administrator chooses to attack their own website - there are other issues at hand than XSS vulnerabilities.

We've updated our demo in the past to reflect this issue by simply sanitizing our demo, since it's one of the rare cases of a public WonderCMS installation, and the admin - attacker can be anyone. This is not the case with other WonderCMS installations.

Please note that WonderCMS wants to enable its users to use JavaScript freely by default.
Feel free to re-open this discussion if you feel it's needed.
