### ISSUE TITLE
Persistant update notification | Summernote button size

### ISSUE THREAD

**Issue by AndiLeni** [robiso/wondercms#39]
Hello,
I found several issues which I could not resolve.

The first issue is the notification which says "New WonderCMS update available." When I click on "Update WonderCMS" the success message shoows up but the notification itself won't disappear.

The second one has to deal with the summernote plugin. The buttons of the editor don't have the same height. In the developer console I could not find any css class which overrides the default values for the buttons.

Hopefully someone can help me :)

Regards
AndiLeni

**Comment by robiso** [comment]
Hello AndiLeni.

Please answer a couple of question to make the assistance faster.
1. Have you ever successfully used the update before?
2. When you open the settings panel, what version of WonderCMS does it show you?
3. Are you coming from a clean install of WonderCMS?
4. Do you know what version of PHP you're running and on what server (Apache, NGINX, IIS)?

I'm sure more question will arise such as (if you're coming from an older version):
1. Did you update the summernote plugin manually, or is this a clean install?
2. Were the summernote buttons fine before the update (if you are in fact coming from an update)?

**Comment by AndiLeni** [comment]
1. No, it is the first time I tried WonderCMS
2. 2.3.0
3. see 1.
4. I installed Wondercraft on my local webserver using MAMP. Apache, PHP 7.0.9

Everything was installed freshly.

**Comment by robiso** [comment]
Somebody had a similar issue before on a local installation, because of a missing certificate on the local machine:
https://github.com/robiso/wondercms/issues/33

@halojoy solved this with
> I downloaded a certificate from the cURL website.
> cacert.pem
>  So now it works alright.

You could turn of the cerificate check for cURL, but it's bad practice and considered unsafe as it enables  MITM (Man In The Middle) attacks, so please use the above solution to solve your problem.

**Comment by robiso** [comment]
Just to add, this can be fixed on your local machine by install the certificate as posted above. So it would work with your MAMP installation without any problems, thus reducing the need to test it on a "real" host.

**Comment by AndiLeni** [comment]
I skipped the prozesss to install a certificate and simply added the line
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);`
to the `_getExternalFile` function.
The update notification is now working as expected but the Summernote plugin still does not work.

**Comment by AndiLeni** [comment]
UPDATE:
For further reference and if someone might has this problem too here is the solution.
In my php.ini file `display_errors ` was set to `on` which forces the browser to render a warning, notice, error, etc. before the `<!DOCTYPE html>` tag. As seen in your link to stackoverflow the problem was caused by a wrong doctype.

Example:

```
<br />
<b>Notice</b>:  Undefined index: token in <b>C:\MAMP\htdocs\wCMS\index.php</b> on line <b>408</b><br />
<br />
<b>Notice</b>:  Undefined index: token in <b>C:\MAMP\htdocs\wCMS\index.php</b> on line <b>365</b><br />
<!DOCTYPE html>
```

**Comment by robiso** [comment]
As I stated before: turning of the certificate check (with `curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);`) instead of actually installing the certificate is considered bad practice, unsafe - **it enables MITM (Man In The Middle) attacks**.

Regarding the Summernote plugin, we have nothing to do with the actual styling of the plugin except for turning off the background to transparent. I tried Googling for your problem and the only thing I came up with was: https://stackoverflow.com/questions/24594828/summernote-buttons-varying-height.

You can open a seperate issue about this as this is not a part of WonderCMS. Summernote is a seperate project, and a WonderCMS plugin was made by Prakai Nadee, I only patched up the vulnerabilities and turned off the Air mode. When you open a new issue in the plugins section, make sure to post a screenshot or a demo example on your server.
--
The cause for those errors is because we've missed to check if the REQUEST[TOKEN] exists before putting into an if statement. Closing this issue and issuing a patch soon.

Note: the patch won't fix the cURL certificate error you're having. Updating WonderCMS to a newer version overwrites any changes you've made to index.php. If you need to make changes, you can do so with the functions.php file or a plugin, check our wiki (https://github.com/robiso/wondercms/wiki) for more info.

**Comment by robiso** [comment]
// Edit, here's the fixed index.php, you should not be getting any more errors. Please confirm.

[index.php.zip](https://github.com/robiso/wondercms/files/1246673/index.php.zip)

**Comment by AndiLeni** [comment]
Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in C:\MAMP\htdocs\wCMSold\index.php on line 406

**Comment by robiso** [comment]
Found the type, please try again.
[index.php.zip](https://github.com/robiso/wondercms/files/1246695/index.php.zip)

If everything goes well, let me know. Can you please post your first name / last name and link to website so we can link to it on https://wondercms.com/whatsnew

**Comment by AndiLeni** [comment]
I guess you posted the wrong file. The first one you gave me and the second one are the same :)

My name is Andreas Lenhardt.

**Comment by robiso** [comment]
Here comes the right one:
[index.php.zip](https://github.com/robiso/wondercms/files/1246803/index.php.zip)
We'll list you just by name, any website links, or maybe Twitter?

**Comment by AndiLeni** [comment]
Parse error: syntax error, unexpected ')' in C:\MAMP\htdocs\wCMSold\index.php on line 406
A `)` too much. If I remove it it's fine.

You can link to: https://twitter.com/AndiLenhardt

**Comment by robiso** [comment]
Sorry for the hassle, one last time attaching the corrected ZIP.
[index.php.zip](https://github.com/robiso/wondercms/files/1247154/index.php.zip)

If you don't mind running it for a test one more time. This will be dispatched as version 2.3.1 within the next 24 hours.

Thanks @AndiLeni.

**Comment by robiso** [comment]
Patch for the two "is sets" deployed with 2.3.1.

@AndiLeni, we have thanked/linked to you on the following locations:
- https://wondercms.com/whatsnew
- https://github.com/robiso/wondercms/releases/tag/2.3.1
- https://wondercms.com/forum/viewtopic.php?f=8&p=1833#p1833
We have additionally added you to our special contributors list
- https://www.wondercms.com/special-contributors
Also on the WonderCMS download page
- https://www.wondercms.com/latest

Thank you. :)

**Comment by AndiLeni** [comment]
There are still some warnings which didn't occur before. Are you sure you didn't mix up some files accidentally?

```
Notice: Undefined index: token in C:\MAMP\htdocs\wCMS\index.php on line 407
Notice: Undefined index: token in C:\MAMP\htdocs\wCMS\index.php on line 364
```
Both of them can be fixed using `isset()`

**Comment by robiso** [comment]
Are you sure this happens with the latest 2.3.1 version? Here's the official index.php:
https://github.com/robiso/wondercms/blob/master/index.php
Both of those lines you're reporting have an isset check in the official repository.

**Comment by AndiLeni** [comment]
Well, obviously this time I messed stuff up.
My fault, sorry!

**Comment by robiso** [comment]
We're only human. :)
