### ISSUE TITLE
WonderCMS 2.3.1 warnings on clean install

### ISSUE THREAD

**Issue by peterb776** [robiso/wondercms#46]
I've just done a first time install of 2.3.1 and get the following notices:

Notice: Undefined index: token in C:\xampp\htdocs\sde\index.php on line 407

Notice: Undefined index: token in C:\xampp\htdocs\sde\index.php on line 364

**Comment by anolis** [comment]
Hello @peterb776, can you please provide us details of your server environment so that we may better help you?

Please let us know, web server and version as well as PHP version. Thanks!

**Comment by peterb776** [comment]
I'm running XAMPP Version 5.6.24 on Windows 10 as a local development environment, which means:
  - Apache 2.4.23
  - PHP 5.6.24 (VC11 X86 32bit thread safe) + PEAR

The environment runs WordPress 4.8 without problems.

Regards,
Peter

**Comment by peterb776** [comment]
Sorry, should also have pointed out that the messages only appear when I login, as in the attached screenshot:
![wondercms-messages](https://user-images.githubusercontent.com/10865376/31351832-75f4c100-ad24-11e7-963b-42f534258c34.jpg)

The "Update WonderCMS" message always appears, even though it's the latest version, and if I try to install plugins then it says "Installed successfully" but the plugin has not been installed!

Regards,
Peter

**Comment by robiso** [comment]
Hello @peterb776.

This is happening due to the fact your local machine (server) doesn't have a certificate.
Please check our wiki for this issue, we also provide a couple of links which basically instruct on how to install the certificate.
 - https://github.com/robiso/wondercms/wiki/Persistent-%22New-WonderCMS-update-available%22-message

Solution recap:
- You are running WonderCMS on a local computer and cURL does have a certificate.
-  Solution: install a certificate on your local computer: https://stackoverflow.com/questions/14987857/what-exactly-is-cacert-pem-for
This message will/would not be showing up on production servers.

The "Installed successfully" message is probably happening because of the same reason above. Try installing the certificate and this should work. After that, installing plugins will work normally.

Regarding to the "undefined index" errors: we already have a fix and we're preparing for a roll-out soon, if you want, you can try out the beta pre-release:
https://github.com/robiso/WonderCMS-testRepo/blob/master/index.php

**Comment by peterb776** [comment]
I've installed the beta and it seems to work fine. I'll report any problems that do occur.

Please note that my local machine **does** meet the requirements (as stated in the page dated 22 Aug 2017): it **does** have cURL running. You need to update the requirements list to state that an SSL certificate is needed, because it doesn't say that this is necessary. (Or better still, move the plugin and theme files to a non-https location so that newbies with http sites don't run into this problem.)

I avoided the need for the certificate by downloading the zip files in a browser and placing them in the root of my server.

Regards,
Peter

**Comment by robiso** [comment]
Your machine does indeed meet the requirements and cURL itself missing isn't the problem, the lack of the certificate list is. This isn't a traditional https:// requirement, but almost every server I've seen (that is not local), meaning shared/dedicated, has this certificate list fetched. I'm running on a http:// website and installing plugins without an issue (not on a local machine though). Maybe just a warning in the wiki for users that set up local servers would suffice?

Here's a issue thread: https://github.com/robiso/wondercms/issues/39 where someone had the same problem on a local machine with all the requirements being met,  but still ran into the persistent "update" message due to the missing certificate. The user chose to disable the certificate check with PHP in their local WonderCMS, but that opens up an attack surface for an MITM attack, as described in the mentioned thread. The user didn't plan on using this server for production.

On another note, treat your local server good with a free cert from cURL :)
https://curl.haxx.se/docs/caextract.html

Thank you very much for your input @peterb776, let me know if you think the above would suffice, since moving the plugins elsewhere than GitHub seems like a hard choice to make. I'm open to discussion on how to properly solve this.

**Comment by peterb776** [comment]
It would be a good idea to at least put a warning in the wiki, as I almost gave up on WonderCMS when I hit the problem. If I hadn't already had a github account then I probably wouldn't have bothered, and moved on to trying other CMSs.

For the moment I've disabled the update check in index.php so that I can get on with trying to build a theme.

Peter

**Comment by robiso** [comment]
To prevent other users going through the same frustration, the certificate note is added on:
- WonderCMS wiki (DO list)
  - https://github.com/robiso/wondercms/wiki
- WonderCMS github page/readme
  - https://github.com/robiso/wondercms
- WonderCMS website (requirements)
  - https://www.wondercms.com/requirements
- WonderCMS download page (frequent questions)
  - https://www.wondercms.com/latest
- WonderCMS wiki List of common errors
  - https://github.com/robiso/wondercms/wiki/List-of-common-errors

Thanks again for your awesome feedback. How are you liking WonderCMS so far? (other than the hiccups you've gone with the Update message).

**Comment by peterb776** [comment]
It's going well at present. I've installed summernote and modded it to remove the font size, color and text alignments from the menus as I want my client to stick to the agreed style in the CSS.

I'm now going through the theme - a free single page, multi-section portfolio HTML5/CSS design - replacing the content sections with theme tags. This will take a few days of my spare time as I'm doing it one section at a time and checking for mistakes at each stage, but it looks simple enough.

**Comment by robiso** [comment]
Sounds good. Here are a couple of additional tips:
- You can use custom blocks for your sections, so each section is a block (an example of a custom block is the footer) wiki: https://github.com/robiso/wondercms/wiki/Create-new-editable-areas-%28blocks%29
- If you want to show some content only on a specific page, you can use the code below (in your theme.php).

```
<?php if ( wCMS::$currentPage == 'home' ) ?>
	<div class="container">
		<?=wCMS::block('customBlock')?>
		<p>We can load a block, or a hard coded text.</p>
	</div>
<?php endif ?>
```

If you run into any problems/questions, check out the community: https://www.wondercms.com/community.
