### ISSUE TITLE
Dependencies Update

### ISSUE THREAD

**Issue by Tangol** [robiso/wondercms#49]
I've noticed that WonderCMS still uses jQuery 1.12.4 for compatibility with old browsers like IE 6-8.
I believe that's not the case anymore, as [statistics](https://www.w3schools.com/browsers/browsers_explorer.asp) show that older browsers have 0 usage.

So for security and performance reasons, with the release of [WonderCMS 2.4.0](https://github.com/robiso/wondercms/issues/48), I think it would be better to switch to **[jQuery v3.2.1](https://jquery.com/)**

Also, **[jquery.autosize](https://github.com/jackmoore/autosize/releases)** & **[taboverride](https://github.com/wjbryant/taboverride/releases)** need an update.

**Comment by robiso** [comment]
The reason we're still using 1.12.4 is because it's still the most popular and most cached of them all:
- source: https://w3techs.com/technologies/details/js-jquery/1/all
Once the internet is ready for the "switch", we'll be also prepared to switch to the latest 3.2.1 cdn, it will probably be even a newer version by then available.

I'll be implementing the latest autosize and taboverride, thank you!

**Comment by robiso** [comment]
Implemented, will push into effect with the Jan 1, 2018 release.
