### ISSUE TITLE
[SVG feature - public discussion] SVG XSS on file upload

### ISSUE THREAD

**Issue by Tanmay9511** [robiso/wondercms#56]
Hi Team,

I have found stored Cross-Site scripting on WonderCMS 2.4.0

In Index.php there is a function "uploadFileAction()"

It does not sanitize svg file and it is possible to execute a Cross-Site Scripting XSS attacks.

Already sent email to info@wondercms.com, and work with all modern browser. hope you can fix it asap.

![xss](https://user-images.githubusercontent.com/36262050/35967991-9854a958-0ce8-11e8-9255-2fb592e61b93.jpg)

When you fix the bug, please, can you include my name in the release notes when the bug will be corrected? Tanmay gtanmaynashte@gmail.com

**Comment by robiso** [comment]
Hello @Tanmay9511.

This seems to be a feature in the way how SVG works.
As you probably know, SVG is not only an image but also a sort of an app, which also supports JavaScript amongst other things.

# DISCUSSION - we have 2 options || Please share your opinion!
1. Remove SVG functionality altogether.
2. Add a notice to administrators - "WonderCMS supports SVG by default, which brings responsibility for administrators." In this second case, we keep the functionality as it it and warn about the "power" this responsibility brings.

There is a third option (unknown to me at this stage), is to sanitize SVG's and cripple their functionality.

**This does not seems like an urgent fix**, since it takes multiple conditions for this vulnerability to take place.
1. The attacker must be admin and logged in as admin.
2. The attacker must be logged in to upload a SVG (as admin).

**Comment by robiso** [comment]
Here's a take at how WordPess solves it - **they don't allow SVG's to be uploaded (although there's a plugin that allows them to be uploaded.**

This seems like a sensible choice from WordPress, since they have multiple users. However, WonderCMS **has only one user, which would mean the admin is the only point of entry for an attack.** If the user is already an admin, they can do so much more damage than a SVG XSS attack.

**Comment by PiersMorgan** [comment]
In my opinion no changes are needed here. If you are logged in as admin by that point you can basically destroy the CMS internally, why would you want to XSS if you are 1. Logged in as essentially the root user of the website in question. 2. All the XSS vulns people are finding all require an admin to be logged in. That sort of defeats the object of XSS as the whole point would be to find vulnerabilities where you can XSS WITHOUT being logged in.

**Comment by robiso** [comment]
Additionally arranged to have added this discussion on the official WonderCMS contact page:
- https://www.wondercms.com/contact

Link to the discussion of "bug's we won't be fixing": https://github.com/robiso/wondercms/issues/57

**Comment by robiso** [comment]
Closing this issue.

Feel free to continue this discussion here: https://github.com/robiso/wondercms/issues/57
