### ISSUE TITLE
Plugin Modern Setting error

### ISSUE THREAD

**Issue by dudulxyz** [robiso/wondercms#61]
Hi,
Plugin Modern Setting runing on wcms version 2.4

Catchable fatal error: Object of class stdClass could not be converted to string in
plugins/_modern_settings/_modern_settings.php on line 180

**Comment by robiso** [comment]
@dudulxyz, this plugin is not the approved plugins list (since a while ago): https://www.wondercms.com/plugins

You can contact the plugin author on the below link and kindly ask if he would be prepared to port the modern settings plugin to the latest WonderCMS version.
Modern settings plugin author: https://github.com/prakai/wcms-_modern_settings
