### ISSUE TITLE
[Feature implemented in dev branch] Having a default passord that is the same everytime is dangerous

### ISSUE THREAD

**Issue by NicolasCARPi** [robiso/wondercms#85]
In the real world, some users never change the default password. So having a default password of 'admin' creates a security issue. Same with the loginURL. It seems it should be changed after install so why not have an already hard to guess one from the start?

My suggestions:

* generate a random password on first run instead of 'admin', or just login the first visitor to the admin panel and force him to set a password immediatly before accessing other functions
* generate a random loginURL on first run

Because I'm still not familiar with your code base I'm opening an issue instead of a PR ;)

**Comment by robiso** [comment]
@NicolasCARPi, commited the following changes to the dev branch:
- added random password generator,
- changed minimum password requirement to 8 characters,
- replaced "VERSION" with 2.6.0 in the create database function, as the DB version can sometimes be different from the CMS version. It's easier to keep track with database migrations that way.
https://github.com/robiso/wondercms/commit/abd057fe9df9457e4917b66b93efa3f9fc140821

**Comment by NicolasCARPi** [comment]
Some remarks:

* you shoulduse mb_strlen to check the size. See this example: https://3v4l.org/iPsZV
* you should avoid magic numbers: so add a new constant called "MIN_PASSWORD_SIZE" at the top and use that to compare the size everywhere in the code.
* I would rename the variable "generateRandomPassword" to just "randomPassword", as it feels weird for a variable to have an action verb (it would fit more a function in fact). So I would even recommand to extract the password generation to a private function (called getRandomPassword() for instance).

Each function should do one thing only. This improves code quality overall. And make things clearer. And allows for reusing in other parts of the code without having to copy paste code ;)

**Comment by NicolasCARPi** [comment]
No the 8 doesn't need to be in quotes as it's an integer, not a string. And it's LENGTH, not LENGHT ;)

And the line should be:

`wCMS::alert('danger', sprintf('Password must be longer than %d characters.', MIN_PASSWORD_LENGTH));`

But in fact instead of using define and making it global, it would be best if it was a property of the class:

~~~php
class wCMS
{
     private const MIN_PASSWORD_LENGTH = 8;

...
wCMS::alert('danger', sprintf('Password must be longer than %d characters.', self::MIN_PASSWORD_LENGTH));
~~~

**Comment by robiso** [comment]
@NicolasCARPi, works like a charm and committed your idea to the dev branch: https://github.com/robiso/wondercms/commit/1dfd2e5377024562dcd3b9c4aa151dbfdf314ca3

Do you possibly know what I'm doing wrong when creating a private function for the password generator and the password that is displayed to the user is different than the one saved in the database?

**Comment by NicolasCARPi** [comment]
> Do you possibly know what I'm doing wrong when creating a private function for the password generator and the password that is displayed to the user is different than the one saved in the database?

Probably because in createdatabase you need to have:

~~~php
$password = wCMS::getPassword();
~~~

And that's what you include in the db, not a call to the function because it will return a different one everytime.

**Comment by NicolasCARPi** [comment]
I left some comments on the commit.

We'll have to talk about fetching stuff from the repo as this is 1. not done properly (what if github is down?) 2. not the canonical way of doing this. Example: why fetch the second .htaccess from github when it's already available in the current directory? Also, imagine the version stored on github is not compatible with the version installed, it can create issues. Whereas using the one already there, not.

**Comment by robiso** [comment]
@NicolasCARPi, appreciate the comments, fixed the mistakes I made.

About the fetching stuff from the repo:
- since WonderCMS is free, I would say it's safe(r) to rely on GitHub's servers than any of my own. Though there could be an additional check added if GitHub is down or available when fetching the files.

What I've been doing until now is, I manually created a ZIP file of the 4 files (index.php, theme.php, style.css, .htaccess) after each WonderCMS release, so the htaccess-ultimate was actually never included in the ZIP file. I do understand your concern about the incompatibility.

I agree there needs to be a better solution for updating the admin.css, admin.js, index.php and probably the htaccess file. Possibly even the default theme. I've already started including version files in the themes/plugins in the past, with the hope of someday being able to update them through WonderCMS itself (as in "New theme/plugin update available") and not via Settings-> Themes & plugins.

Currently the users have to copy/paste the theme/plugin URL and select "Update" in the Themes & plugins part of the settings of WonderCMS.

**Comment by NicolasCARPi** [comment]
BTW, instead of manually creating a zip file with only the core files, why not get the zip from github with all the files? At the end of the day I think nobody cares about the number of files/folder, it's not like we're in the 70's and disk space is expensive. Keep in mind that no actual users will read the index.php file (and you better hope they don't or they might get scared!). The archive can be 30K or 60K, it's the same, unzipping/downloading is instantaneous. Another way to go would be to have some sort of CI building a custom zip on each commit/release, and you would add the "compiled" zip to the release page and on the website. But it needs to be automatic, something along the lines of:

git clone repo
yarn install
grunt
zip -r release.zip <list of files included>

This way users would still be able to get the zip and unpack it and it just works.

This would also allow us (the devs) to remove the minified files from git tracking and have more liberty about everything (like using composer) and bring wcms up to standards.

To sum up: there would be a build step for git installs, but for zip install it'll work as before as the zip will be "built" (minifying assets) and provided as a release.

Also, I believe there should not be two .htaccess, but only one, with the secure headers. Because the button in admin panel to "make the site more secure but it can break everything" is something to get rid of. I can help with that. See: https://observatory.mozilla.org/analyze/www.elabftw.net. You see the score of 115/100? That's what we should aim for a default install of wcms. And the wiki should be there to help users set up HTTPS with their webserver and let's encrypt.

Also, because .htaccess makes the site slower, sending the security headers in PHP might be something to consider. Also, it would mean that it would work for all servers without any configuration. I'm partial to sending security headers with the webserver but there is honestly no difference if it's PHP sending it.

Of course, all these changes will prove a bit difficult to implement or messy unless we get rid of the "single page app". And this is where you need to take a decision and decide what you want to do. Here is how I see it:

**What we want:** 

* something that can be unzipped and work immediatly (if the correct permissions are set).
* something relatively straightforward and simple
* something that can be actually worked on by other PHP devs without them running the other way, scared by this one huge static class and the (very bad) overuse of ternary operators. As an exercise for the reader, try to figure out what this does:
https://github.com/robiso/wondercms/blob/dev/assets/admin.js#L23

Yes, this is one HUGE line, and this is AFTER deobfuscating the code. There is still some work ;) Note: ternary operators should be used with caution and scarcity. The cognitive load to understanding some part of the code is huge, and there is absolutely NO added value in using it. Exercise n°2: try to figure out what this does: https://github.com/robiso/wondercms/blob/dev/index.php#L1038

BTW, if you run the previous line in a static analyzer, you realize the parenthesis are wrong:
![2019-01-21-032909_1130x56_scrot](https://user-images.githubusercontent.com/3043706/51716810-a46a4580-203e-11e9-9d78-ba2ac8bff4e6.png)

See how the argument of strtolower is a bool?

I hope I managed to convince you that code readability is paramount. Don't be fooled by conciseness, it brings nothing good. Only bugs and headaches.

IMHO, a lot of things can be kept as-is, but with some modifications, it can become much, MUCH better, much easier to work with and detect bugs, test it automatically (having something like [this](https://circleci.com/gh/elabftw/elabftw/tree/hypernext) helps a lot!). Basically, address all the criticism you get when you post to r/php.

The other solution is to keep this single index.php file because you're attached emmotionally to it and you want to keep your project unmaintainable and stuck in 2006. But you've given signs that you're willing to move forward, so I'm hoping you'll agree to have PSR-4 autoloading and use some dependencies to make life easier, site more secure, etc…

I think I've written a lot, but there are lots of things to discuss and improve. I'm basically probing to see how far you're willing to go. And I'll reiterate: having maintainable code with a build step (yarn install; grunt; composer install) doesn't mean we need to abandon the "unzip and work" workflow/feature. It just means you'll need to provide a "built" zip for releases, that's it. If you look around, you'll see a lot of software is doing this.

**Comment by robiso** [comment]
> BTW, instead of manually creating a zip file with only the core files, why not get the zip from github with all the files? At the end of the day I think nobody cares about the number of files/folder, it's not like we're in the 70's and disk space is expensive.

I would partially disagree on this point. After all, this is what got WonderCMS listed on the "Microsoft Azure" and how wcms received it's first larger group of supporters/users searching for "smallest cms" and different variations. From a "marketing" perspective, it does carry value and some importance. **On the other side (from a developers perspective) this is of course bad and ia preventing wcms from being supported by devs in general, thus limiting itself to a certain growth potential.**

The wcms goal is still to remain tiny, and I would personally not like to see it over-bloated with features as most of the other CMS'es do it. I'm not implying that you would add more features, it's just a minor note. This is what currently differentiates us from anyone else and at least a few things could be kept "unorthodox" (as you've put it).

> Also, I believe there should not be two .htaccess, but only one, with the secure headers. Because the button in admin panel to "make the site more secure but it can break everything" is something to get rid of. I can help with that. See: https://observatory.mozilla.org/analyze/www.elabftw.net. You see the score of 115/100? That's what we should aim for a default install of wcms. And the wiki should be there to help users set up HTTPS with their webserver and let's encrypt.

I agree the default wcms installation could be safer with appropriate headers (I don't think it really matters if it's with htaccess or PHP, with the latter (PHP) probably bringing more flexibility), but I would like to keep some sort of options for users that won't be able to upgrade to HTTPS just yet, and for local installations + users that are using wcms on free hosts.
Example of current HTTPS usage among top 1 million websites: https://statoperator.com/research/https-usage-statistics-on-top-websites/
Otherwise I wholeheartedly agree the whole internet should just move to HTTPS already.

**With that being said, I realize some compromise has to be made.**
> What we want:
>- something that can be unzipped and work immediately (if the correct permissions are set).
>- something relatively straightforward and simple
>- something that can be actually worked on by other PHP devs without them running the other way, scared by this one huge static class and the (very bad) overuse of ternary operators.

You seem to pretty much understand where I'm accepting the compromise as I agree (although not light-heartedly) on all of your points.

> IMHO, a lot of things can be kept as-is, but with some modifications, it can become much, MUCH better, much easier to work with and detect bugs, test it automatically (having something like this helps a lot!). Basically, address all the criticism you get when you post to r/php.
> 
> The other solution is to keep this single index.php file because you're attached emmotionally to it and you want to keep your project unmaintainable and stuck in 2006. But you've given signs that you're willing to move forward, so I'm hoping you'll agree to have PSR-4 autoloading and use some dependencies to make life easier, site more secure, etc…
> 
> I think I've written a lot, but there are lots of things to discuss and improve. I'm basically probing to see how far you're willing to go. And I'll reiterate: having maintainable code with a build step (yarn install; grunt; composer install) doesn't mean we need to abandon the "unzip and work" workflow/feature. It just means you'll need to provide a "built" zip for releases, that's it. If you look around, you'll see a lot of software is doing this.

Leaving the emotional attachment aside, I am willing to go away from the single page app. I think we should accept the fact that we will lose some user base, for the price of developers being able to use WonderCMS in a dev-friendlier way.

**I'm wondering and would like to start a discussion - what would these changes mean for WonderCMS and how should the next version(s) be planned?**
- I would like to release 1 more version that doesn't break backwards compatibility (eg. v.2.7.0) and add multiple warnings about that being the last version before big changes coming ahead.
  - I will probably create a seperate branch for this version.
  - The version 2.7.0 would be still available for download, without any themes or plugins and left completely unsupported after version 3.0.0 is released.
- **After the 3.0.0 update, all themes, plugins and documentation would have to be updated, as they're all working with the single class wCMS.**
  - With v3.0.0, break WonderCMS into multiple files.
  - Include an updater for all those necessary files (possibly even themes/plugins).
  - Include the compatibility check (the one you've drastically improved here: https://github.com/robiso/wondercms/issues/73#issuecomment-453278386)
  - Possibly leave an option for HTTPS - on/off switch

**Comment by NicolasCARPi** [comment]
> I'm not sure this is a step in the right direction for wcms. Until now, there haven't been any issues using the one click updater and rewriting the index.php. I would really insist on keeping some sort of update feature.

That's because up until now your project was in a single file. This made the update easier, but also the friendliness of the file for a potential developer atrocious. Hence the necessity to split the project in several files (as we did for the CSS and JS). Also, I see your `update()` is just getting the latest `index.php` file from the repo. So what if you changed stuff in the default theme? The user won't get it. But you are right, that doesn't mean this option should be removed. A similar thing can be done for all the files in the repo. But it means that ALL files must be writable by the webserver. Not necessarily an issue I think. But there should be a way to show release notes before updating. Right now I'm not focussing on the update part, but I'll keep your comment in mind.

> I would really not like to over-bloat wcms with features/plugins. 

The way I see it, adding pre-installed plugins that are disabled by default is not bloat, it's a way for the final user to be able to switch them on immediatly. But if you want to keep it like that, and fetch them from an URL, sure.

> Would adding composer and any libs prevent ordinary users that aren't composer users to simply edit index.php or any other file without any additional tools?

No. BTW, if you're a PHP dev and you don't have composer installed in 2019, there is something wrong. Note: installing composer can be done by the user in the current directory (see [the 4 lines install](https://getcomposer.org/download/)). And then one command (`composer install`) and you're done. And there is absolutely no difference about editing a file!

> For example, would I still be able to unzip and upload files and edit any file I want without any additional requirements?

That's what I dicussed: you can release a pre-built zip file with all the necessary files inside. No composer required, no yarn required. So the answer is yes.

> What changes would composer bring? It is really necessary and is it possible to keep it as plain as possible?

Composer is just something useful to load PHP dependencies and autoload your classes. And PHP dependencies are useful to avoid reinventing the wheel (badly). Let me illustrate: what is better between a 560 characters single line with at least 3 bugs inside and very complicated to understand and edit:

![2019-01-27-063320_942x91_scrot](https://user-images.githubusercontent.com/3043706/51797074-a3334700-21fd-11e9-9e21-8e6d50040d16.png)

Or this:

![2019-01-27-063349_922x74_scrot](https://user-images.githubusercontent.com/3043706/51797075-a8909180-21fd-11e9-89af-96f8525873e9.png)

?

You seem to be concerned with the possibility for a lambda person to be able to open the index.php file and find out how it works. But the absence of code comments, type hintings, the overuse of ternary operators, the one gigantic file with over 1000 lines and the very long lines really are going against readability. Much more than using composer (the thing ALL PHP projects use), or having code properly split between a few files (remember the CSS and JS that were obfuscated?). With the changes you merged, it's much better than before, and with the ones I'm currently writing, it'll be much much easier for someone to dive into the code. My point being that wanting users to be able to see and read the code is antinomic with the way the code is on the master branch right now. Also, I think you need to realize that actually very few of the people that install wcms actually look at the code (well that's what I think, I don't have numbers to prove it :p). Having a small and readable codebase is compatible with the changes I'm bringing. I'm not trying to add code, but rather reorganize it in a way that allows to remove some of it.

> Wouldn't removing htaccess take away having clean URLs (which is really important) and also give direct access to the database.js file? Or did you just mean take out the security headers out of the htaccess file?

Yes, I'm only talking about the security headers.

> I would really keep some things extremely simple and would not include unnecessary tools if there are possible workarounds for them. Hope you understand/see that the goal isn't to be like every other CMS.

I see. But believe me, you're not like ANY other CMS :D Currently I've edited quite a lot of code to implement the changes I listed, and it's still very awkward and unorthodox, as you like it :)

I'm just trying to fix the very big number of issues that exist in the code. It's almost 7am, I spent probably 10 hours on the code today (I think I enjoy rewriting projects a lot ^^). And let me tell you there was A LOT of things to improve/fix. I managed to bring [psalm](https://getpsalm.org/) static analysis results from 48 errors and 35 issues to 0 errors and 4 issues. Honestly, sometimes I'm even wondering how it was working (hint: because PHP is forgiving). With the type hinting it becomes much easier to spot bugs. You'll also see that I've made some things much clearer and much straightforward. In fact, a lot of times I was able to refactor the code, that means making it shorter and more robust. Because a line not written is a line without bug, I always aim for shorter code. For instance, the backup related code was a complete mess and not very logical (in the function signatures or code ordering). You'll see how it is much cleaner now, while still retaining the same functionalities (backup the whole root folder). The list of things I fixed is very long, but there were things like having a `null` argument in a PHP function that doesn't accept `null` there (but a string). A lot of these things are actually very easy to spot and fix by running static analyzers. Something you should get into the habit of using (maybe not now as the number of errors on master/dev is overwhelming :p). Also, calling private functions from the theme, I'm not sure how you selected which functions were private and which were public because it's pretty much the inverse of how it should be. On one hand you managed to build something very advanced a quite smart, and on the other hand there are errors that are very basic all across the code. I also removed all the static stuff, you'll see how that allows to simplify the code and make it more robust (I'm making teasers :p).


Note: right now I'm using composer for two things: http-foundation (the Request object), and autoloading the class. But I think it's totally doable to get rid of it, implement correctly the url() function, and load the class manually (as there is only one we probably don't need PSR-4 autoloading). I'll keep it for now but I might remove it before making the PR. But if at some point we want to add let's say **tests** (and we definitely want that), composer will already be there and make our life soooo much simpler. I think you just don't see how ubiquitous it is in the PHP ecosystem. That brings me back to my very first comment on this repo, where I was inviting you to try and build another app with a PHP framework or two, just to see how modern PHP looks like and come back with a better way to structure code in mind.

Going to sleep now!

**Comment by robiso** [comment]
> Also, I see your update() is just getting the latest index.php file from the repo. So what if you changed stuff in the default theme? The user won't get it. 

When there was an update in the default theme, I included the "updateOtherFiles()" function, with additionally updated the theme.php as mentioned in one of my posts here: https://github.com/robiso/wondercms/issues/92#issuecomment-455858731 (bottom part of code). If the dbVersion in the database was smaller than the previous version, the theme.php and style would be updated.

> No. BTW, if you're a PHP dev and you don't have composer installed in 2019, there is something wrong. Note: installing composer can be done by the user in the current directory (see the 4 lines install). And then one command (composer install) and you're done. And there is absolutely no difference about editing a file!

My "mediocreness" is showing up a bit here, since I haven't had to use PHP for anything at the job I'm currently at (I'm not sure I will be developing anything valuable in the future), or maybe when I get my health related condition treated (right now, each time I look at PHP, it feels like I've forgotten everything, this is why I also find upgrading any knowledge I have, very difficult, as everything flows out of my memory really fast).

> Composer is just something useful to load PHP dependencies and autoload your classes. And PHP dependencies are useful to avoid reinventing the wheel (badly). Let me illustrate: what is better between a 560 characters single line with at least 3 bugs inside and very complicated to understand and edit:

Thanks for clarifying, seems much, much neater!

> Also, I think you need to realize that actually very few of the people that install wcms actually look at the code (well that's what I think, I don't have numbers to prove it :p). Having a small and readable codebase is compatible with the changes I'm bringing. I'm not trying to add code, but rather reorganize it in a way that allows to remove some of it.

I'm liking your work very much! I think it we can both completely agree on this point, I guess I'm just latching on the point we got the majority of users by being small. For fun, glance at the 300 lines in index.php from November 2016: https://github.com/robiso/wondercms/blob/808440ebc4892263a29335de795e2495dfee42a7/index.php. Good and messy times! Looking forward to some neatness!

> I see. But believe me, you're not like ANY other CMS :D Currently I've edited quite a lot of code to implement the changes I listed, and it's still very awkward and unorthodox, as you like it :)

That's the spirit! 🤣 

> A lot of these things are actually very easy to spot and fix by running static analyzers. Something you should get into the habit of using (maybe not now as the number of errors on master/dev is overwhelming :p). Also, calling private functions from the theme, I'm not sure how you selected which functions were private and which were public because it's pretty much the inverse of how it should be.

A lot of your written text made me LOL really hard. Please keep up the good mood and never stop your comments on "how did it even work" and "most of it is reverse of how it should be".

> On one hand you managed to build something very advanced a quite smart, and on the other hand there are errors that are very basic all across the code. I also removed all the static stuff, you'll see how that allows to simplify the code and make it more robust (I'm making teasers :p).

I am very excited, to say the least. :) You're doing an excellent job and I would love to invite you to the future of WonderCMS and crown you as wcms 🏆 contributor number one! 🏆 

> But I think it's totally doable to get rid of it, implement correctly the url() function, and load the class manually (as there is only one we probably don't need PSR-4 autoloading). I'll keep it for now but I might remove it before making the PR. 

Can I help in any way with implementing the url() function in a better way? I feel like you're nodding your head already. :)

> I think you just don't see how ubiquitous it is in the PHP ecosystem. That brings me back to my very first comment on this repo, where I was inviting you to try and build another app with a PHP framework or two, just to see how modern PHP looks like and come back with a better way to structure code in mind.
Going to sleep now!

You are correct. Even though I said I wouldn't be developing anything of value, I will have to take some time and try to deep dive into something, just to get a feel of how the future is like. Hopefully it will be able to happen in the incoming months. Thanks once again for all your invested hours in this project. While I understand you're a night owl, please don't lose sleep as I don't want you to hate this project because of any possible insomnia!

**Comment by robiso** [comment]
Thanks to @NicolasCARPi, this is implemented in the future version of WCMS. Closing issue - comments are still welcome if deemed necessary.
